sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t joaogameprog/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true joaogameprog/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "DockerReact"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-891613447608"
  bucket_path: "DockerReact"
  on:
    branch: master
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  session_token: $session_token