version: '3'
services: 
  frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build: 
      dockerfile: Dockerfile
      context: .
    ports: 
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app